namespace Net.Leksi.RestContract;

internal static class Constants
{

    internal const string Dot = ".";
    internal const string Semicolon = ";";
    internal const string Colon = ":";
    internal const string OpenBlock = "{";
    internal const string CloseBlock = "}";
    internal const string Using = "using {0};\n";
    internal const string Namespace = "namespace ";
    internal const string Public = "public ";
    internal const string Interface = "interface ";
    internal const string Class = "class ";
    internal const string Indent = "    ";
    internal const string Func = "Func<";
    internal const string BeginGeneric = "<";
    internal const string EndGeneric = ">";
    internal const string Comma = ", ";
    internal const string Space = " ";
    internal const string LeftParen = "(";
    internal const string RightParen = ")";
    internal const string Context = "context";
    internal const string Tchar = "t";
    internal const string System = "System";
    internal const string SystemDot = "System.";
    internal const string NewLine = "\n";
    internal const string QuestionMark = "?";
    internal const string Void = "void";
    internal const string Arrow = " => ";
    internal const string LeftBraket = "[";
    internal const string RightBraket = "]";
    internal const string PropertyFormat = "{0}=\"{1}\"";
    internal const string Async = "async ";
    internal const string Await = "await ";
    internal const string CallControllerMethod = nameof(CallControllerMethod);
    internal const string NewObjectArray = "new object[] ";
    internal const string ConfigureAwait = "ConfigureAwait(false)";
    internal const string Apos = "`";
    internal const string TypeOf = "typeof";
    internal const string TypePropertyFormat = "{0}=typeof({1})";
    internal const string SerializedAttributeFormat = "typeof({0})";
    internal const string EqualSign = " = ";
    internal const string GetRequiredService = "HttpContext.RequestServices.GetRequiredService";
    internal const string GetRequiredService1 = ".Services.GetRequiredService";
    internal const string ControllerContext = nameof(ControllerContext);
    internal const string Return = "return ";
    internal const string StringFormat = "\"{0}\"";
    internal const string Get = "Get";
    internal const string Post = "Post";
    internal const string Put = "Put";
    internal const string Delete = "Delete";
    internal const string Head = "Head";
    internal const string Patch = "Patch";
    internal const string Underscore = "_";
    internal const string NewObject = "new";
    internal const string Converters = "Converters";
    internal const string Add = "Add";
    internal const string Deserialize = "JsonSerializer.Deserialize";
    internal const string Serialize = "JsonSerializer.Serialize";
    internal const string Null = "null";
    internal const string UrlEncode = nameof(UrlEncode);
    internal const string UrlPath = "urlpath";
    internal const string Quot = "\"";
    internal const string Replace = nameof(Replace);
    internal const string DollarSign = "$";
    internal const string SendAsync = nameof(SendAsync);
    internal const string DependencyInjection = "Microsoft.Extensions.DependencyInjection";
    internal const string Private = "private ";
    internal const string Readonly = "readonly ";
}
